Repository pingcap/docs-appdev, pull requests merged in 2021-12, with the labels that each got.

#62 chore: update dispatch for latest docs site
  .github/workflows/dispatch.yml
Labels: require-LGT1, size/M, status/can-merge, status/LGT1, translation/no-need

#51 Fix syntax for creating users and granting permissions
  en/for-django.md
  en/for-go-sql-driver-mysql.md
  en/for-gorm.md
  en/for-hibernate-orm.md
  en/for-laravel.md
  en/for-python-mysql-connector.md
  en/for-sqlalchemy.md
Labels: missing-translation-status, first-time-contributor, size/S, status/can-merge, status/LGT2

#61 Add widecolumn for oom and pushdown for oom
  media/autocommit_selectforupdate_nowaitlock.png
  zh/TOC.md
  zh/tidb-database-development-specification/database-object-design.md
  zh/tidb-database-development-specification/sql-development-specification.md
  zh/tidb-database-development-specification/timeouts-in-tidb.md
  zh/tidb-database-development-specification/transaction-restraints.md
Labels: missing-translation-status, require-LGT1, size/S, status/can-merge, status/LGT1

#65 Update mitigation-of-hot-issues.md
  zh/tidb-database-development-specification/mitigation-of-hot-issues.md
Labels: missing-translation-status, require-LGT1, status/can-merge, size/XS, status/LGT1

#66 autocommit_selectforupdate_nowaitlock
  zh/tidb-database-development-specification/mitigation-of-hot-issues.md
  zh/tidb-database-development-specification/notes-on-auto-increment-columns.md
  zh/tidb-database-development-specification/transaction-restraints.md
Labels: missing-translation-status, require-LGT1, size/S, status/can-merge, status/LGT1
