Repository pingcap/docs-appdev, pull requests merged in 2021-10, with the labels that each got.

#28 Add go-sql-driver-mysql
  en/for-django.md
  en/for-go-sql-driver-mysql.md
  en/for-hibernate-orm.md
Labels: require-LGT1, size/L, status/can-merge, status/LGT2, translation/doing

#35 upgrade latest mysql-connector
  en/for-python-mysql-connector.md
Labels: require-LGT1, status/can-merge, size/XS, status/LGT1, translation/doing

#41 chore: trigger site build
  .github/workflows/dispatch.yml
  .github/workflows/media.yml
Labels: require-LGT1, status/can-merge, status/LGT1, translation/no-need
