Repository pingcap/docs-appdev, pull requests merged in 2021-11, with the labels that each got.

#43 Fix the object of description.
  en/for-gorm.md
Labels: contribution, first-time-contributor, require-LGT1, status/can-merge, size/XS, status/LGT1, type/bug-fix

#44 Add TiDB Database Development Specification Document
  en/_index.md
  en/tidb-database-development-specification/best-practices-for-paging.md
  en/tidb-database-development-specification/database-model-design.md
  en/tidb-database-development-specification/database-object-design.md
  en/tidb-database-development-specification/implicit-type-conversion.md
  en/tidb-database-development-specification/introduction.md
  en/tidb-database-development-specification/jdbc-best-practices.md
  en/tidb-database-development-specification/mitigation-of-hot-issues.md
  en/tidb-database-development-specification/notes-on-auto-increment-columns.md
  en/tidb-database-development-specification/notes-on-indexes.md
  en/tidb-database-development-specification/object-naming-guidelines.md
  en/tidb-database-development-specification/process-specification.md
  en/tidb-database-development-specification/sql-development-specification.md
  en/tidb-database-development-specification/timeouts-in-tidb.md
  en/tidb-database-development-specification/transaction-restraints.md
  en/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  en/tidb-database-development-specification/unstable-result-set.md
  ja/_index.md
  ja/tidb-database-development-specification/best-practices-for-paging.md
  ja/tidb-database-development-specification/database-model-design.md
  ja/tidb-database-development-specification/database-object-design.md
  ja/tidb-database-development-specification/implicit-type-conversion.md
  ja/tidb-database-development-specification/introduction.md
  ja/tidb-database-development-specification/jdbc-best-practices.md
  ja/tidb-database-development-specification/mitigation-of-hot-issues.md
  ja/tidb-database-development-specification/notes-on-auto-increment-columns.md
  ja/tidb-database-development-specification/notes-on-indexes.md
  ja/tidb-database-development-specification/object-naming-guidelines.md
  ja/tidb-database-development-specification/process-specification.md
  ja/tidb-database-development-specification/sql-development-specification.md
  ja/tidb-database-development-specification/timeouts-in-tidb.md
  ja/tidb-database-development-specification/transaction-restraints.md
  ja/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  ja/tidb-database-development-specification/unstable-result-set.md
  zh/_index.md
  zh/tidb-database-development-specification/best-practices-for-paging.md
  zh/tidb-database-development-specification/database-model-design.md
  zh/tidb-database-development-specification/database-object-design.md
  zh/tidb-database-development-specification/implicit-type-conversion.md
  zh/tidb-database-development-specification/introduction.md
  zh/tidb-database-development-specification/jdbc-best-practices.md
  zh/tidb-database-development-specification/mitigation-of-hot-issues.md
  zh/tidb-database-development-specification/notes-on-auto-increment-columns.md
  zh/tidb-database-development-specification/notes-on-indexes.md
  zh/tidb-database-development-specification/object-naming-guidelines.md
  zh/tidb-database-development-specification/process-specification.md
  zh/tidb-database-development-specification/sql-development-specification.md
  zh/tidb-database-development-specification/timeouts-in-tidb.md
  zh/tidb-database-development-specification/transaction-restraints.md
  zh/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  zh/tidb-database-development-specification/unstable-result-set.md
Labels: missing-translation-status, first-time-contributor, size/M, status/LGT2, size/XXL

#47 add TOC file
  ja/TOC.md
  ja/app-dev-overview.md
Labels: missing-translation-status, first-time-contributor, status/LGT2, size/XL

#49 Add tdds documents
  en/_index.md
  en/tidb-database-development-specification/best-practices-for-paging.md
  en/tidb-database-development-specification/database-model-design.md
  en/tidb-database-development-specification/database-object-design.md
  en/tidb-database-development-specification/implicit-type-conversion.md
  en/tidb-database-development-specification/introduction.md
  en/tidb-database-development-specification/jdbc-best-practices.md
  en/tidb-database-development-specification/mitigation-of-hot-issues.md
  en/tidb-database-development-specification/notes-on-auto-increment-columns.md
  en/tidb-database-development-specification/notes-on-indexes.md
  en/tidb-database-development-specification/object-naming-guidelines.md
  en/tidb-database-development-specification/process-specification.md
  en/tidb-database-development-specification/sql-development-specification.md
  en/tidb-database-development-specification/timeouts-in-tidb.md
  en/tidb-database-development-specification/transaction-restraints.md
  en/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  en/tidb-database-development-specification/unstable-result-set.md
  ja/TOC.md
  ja/_index.md
  ja/app-dev-overview.md
  ja/tidb-database-development-specification/best-practices-for-paging.md
  ja/tidb-database-development-specification/database-model-design.md
  ja/tidb-database-development-specification/database-object-design.md
  ja/tidb-database-development-specification/implicit-type-conversion.md
  ja/tidb-database-development-specification/introduction.md
  ja/tidb-database-development-specification/jdbc-best-practices.md
  ja/tidb-database-development-specification/mitigation-of-hot-issues.md
  ja/tidb-database-development-specification/notes-on-auto-increment-columns.md
  ja/tidb-database-development-specification/notes-on-indexes.md
  ja/tidb-database-development-specification/object-naming-guidelines.md
  ja/tidb-database-development-specification/process-specification.md
  ja/tidb-database-development-specification/sql-development-specification.md
  ja/tidb-database-development-specification/timeouts-in-tidb.md
  ja/tidb-database-development-specification/transaction-restraints.md
  ja/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  ja/tidb-database-development-specification/unstable-result-set.md
  zh/_index.md
  zh/tidb-database-development-specification/best-practices-for-paging.md
  zh/tidb-database-development-specification/database-model-design.md
  zh/tidb-database-development-specification/database-object-design.md
  zh/tidb-database-development-specification/implicit-type-conversion.md
  zh/tidb-database-development-specification/introduction.md
  zh/tidb-database-development-specification/jdbc-best-practices.md
  zh/tidb-database-development-specification/mitigation-of-hot-issues.md
  zh/tidb-database-development-specification/notes-on-auto-increment-columns.md
  zh/tidb-database-development-specification/notes-on-indexes.md
  zh/tidb-database-development-specification/object-naming-guidelines.md
  zh/tidb-database-development-specification/process-specification.md
  zh/tidb-database-development-specification/sql-development-specification.md
  zh/tidb-database-development-specification/timeouts-in-tidb.md
  zh/tidb-database-development-specification/transaction-restraints.md
  zh/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  zh/tidb-database-development-specification/unstable-result-set.md
Labels: missing-translation-status, require-LGT1, status/can-merge, status/LGT1, size/XL

#52 Revert "Add tdds documents"
  en/_index.md
  en/tidb-database-development-specification/best-practices-for-paging.md
  en/tidb-database-development-specification/database-model-design.md
  en/tidb-database-development-specification/database-object-design.md
  en/tidb-database-development-specification/implicit-type-conversion.md
  en/tidb-database-development-specification/introduction.md
  en/tidb-database-development-specification/jdbc-best-practices.md
  en/tidb-database-development-specification/mitigation-of-hot-issues.md
  en/tidb-database-development-specification/notes-on-auto-increment-columns.md
  en/tidb-database-development-specification/notes-on-indexes.md
  en/tidb-database-development-specification/object-naming-guidelines.md
  en/tidb-database-development-specification/process-specification.md
  en/tidb-database-development-specification/sql-development-specification.md
  en/tidb-database-development-specification/timeouts-in-tidb.md
  en/tidb-database-development-specification/transaction-restraints.md
  en/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  en/tidb-database-development-specification/unstable-result-set.md
  ja/TOC.md
  ja/_index.md
  ja/app-dev-overview.md
  ja/tidb-database-development-specification/best-practices-for-paging.md
  ja/tidb-database-development-specification/database-model-design.md
  ja/tidb-database-development-specification/database-object-design.md
  ja/tidb-database-development-specification/implicit-type-conversion.md
  ja/tidb-database-development-specification/introduction.md
  ja/tidb-database-development-specification/jdbc-best-practices.md
  ja/tidb-database-development-specification/mitigation-of-hot-issues.md
  ja/tidb-database-development-specification/notes-on-auto-increment-columns.md
  ja/tidb-database-development-specification/notes-on-indexes.md
  ja/tidb-database-development-specification/object-naming-guidelines.md
  ja/tidb-database-development-specification/process-specification.md
  ja/tidb-database-development-specification/sql-development-specification.md
  ja/tidb-database-development-specification/timeouts-in-tidb.md
  ja/tidb-database-development-specification/transaction-restraints.md
  ja/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  ja/tidb-database-development-specification/unstable-result-set.md
  zh/_index.md
  zh/tidb-database-development-specification/best-practices-for-paging.md
  zh/tidb-database-development-specification/database-model-design.md
  zh/tidb-database-development-specification/database-object-design.md
  zh/tidb-database-development-specification/implicit-type-conversion.md
  zh/tidb-database-development-specification/introduction.md
  zh/tidb-database-development-specification/jdbc-best-practices.md
  zh/tidb-database-development-specification/mitigation-of-hot-issues.md
  zh/tidb-database-development-specification/notes-on-auto-increment-columns.md
  zh/tidb-database-development-specification/notes-on-indexes.md
  zh/tidb-database-development-specification/object-naming-guidelines.md
  zh/tidb-database-development-specification/process-specification.md
  zh/tidb-database-development-specification/sql-development-specification.md
  zh/tidb-database-development-specification/timeouts-in-tidb.md
  zh/tidb-database-development-specification/transaction-restraints.md
  zh/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  zh/tidb-database-development-specification/unstable-result-set.md
Labels: missing-translation-status, status/can-merge, status/LGT2, size/XL

#53 fix docker run command
  en/for-django.md
  en/for-go-sql-driver-mysql.md
  en/for-gorm.md
  en/for-hibernate-orm.md
  en/for-laravel.md
  en/for-python-mysql-connector.md
  en/for-sqlalchemy.md
Labels: require-LGT1, size/S, status/can-merge, status/LGT1

#54 chore: list as the first child in TOC
  en/TOC.md
  zh/TOC.md
Labels: require-LGT1, size/M, status/can-merge, status/LGT1, translation/no-need

#50 *: add developer guide (Chinese version)
  media/hot_issue.png
  media/transaction_isolation_level.png
  zh/_index.md
  zh/tidb-database-development-specification/best-practices-for-paging.md
  zh/tidb-database-development-specification/database-model-design.md
  zh/tidb-database-development-specification/database-object-design.md
  zh/tidb-database-development-specification/implicit-type-conversion.md
  zh/tidb-database-development-specification/introduction.md
  zh/tidb-database-development-specification/jdbc-best-practices.md
  zh/tidb-database-development-specification/mitigation-of-hot-issues.md
  zh/tidb-database-development-specification/notes-on-auto-increment-columns.md
  zh/tidb-database-development-specification/notes-on-indexes.md
  zh/tidb-database-development-specification/object-naming-guidelines.md
  zh/tidb-database-development-specification/process-specification.md
  zh/tidb-database-development-specification/sql-development-specification.md
  zh/tidb-database-development-specification/timeouts-in-tidb.md
  zh/tidb-database-development-specification/transaction-restraints.md
  zh/tidb-database-development-specification/unique-serial-number-generation-scheme.md
  zh/tidb-database-development-specification/unstable-result-set.md
Labels: missing-translation-status, first-time-contributor, status/can-merge, status/LGT2, size/XXL

#58 Update TOC.md
  zh/TOC.md
Labels: missing-translation-status, first-time-contributor, size/S, status/can-merge, status/LGT2

#60 chore: update generate pdf scripts
  scripts/merge_by_toc.py
Labels: require-LGT1, size/S, status/can-merge, status/LGT1, translation/no-need
